<a href="https://colab.research.google.com/github/kaitouz/ML-DL/blob/main/OpenEdu/task04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INPUT

In [1]:
# file name
FILE_NAME = 'data.csv'

# Processing

In [2]:
from pandas import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [3]:
df = pd.read_csv(FILE_NAME, index_col='id')
df

X   Y  Class
id               
1   81  83      1
2   53  33      1
3   10  69      1
4   52  78      0
5   43  79      0
6   34  82      1
7   75  47      1
8   58  71      0
9   27  59      0
10  82  33      0

In [4]:
X_train = np.array(df[['X', 'Y']])
y_train = np.array(df[['Class']])



---



In [6]:
import sklearn
from sklearn.neighbors import *

## **Train KNN with *n_neighbors* = 1, *p* = 2 (euclidean_distance)**

In [7]:
neigh = KNeighborsClassifier(n_neighbors = 1, p = 2)
neigh.fit(X_train, y_train.reshape(10, ))

KNeighborsClassifier(n_neighbors=1)

### ANS 1

In [20]:
neigh.kneighbors([[67, 36]], 1)[0]

array([[13.60147051]])

### ANS 2

In [22]:
neigh.kneighbors([[67, 36]], 3)[1] + 1

array([[ 7,  2, 10]])

### ANS 3
Find label with k = 3, p = 2

In [24]:
neigh = KNeighborsClassifier(n_neighbors = 3, p = 2)
neigh.fit(X_train, y_train.reshape(10, ))
neigh.predict([[67, 36]])[0]

1



---



### ANS 4
**n_neigbors = 1, p = 1 (manhattan_distance)**

In [26]:
neigh = KNeighborsClassifier(n_neighbors = 1, p = 1)
neigh.fit(X_train, y_train.reshape(10, ))

neigh.kneighbors([[67, 36]], 1)[0][0]

array([17.])

### ANS 5

In [30]:
neigh.kneighbors([[67, 36]], 3)[1] + 1

array([[ 2, 10,  7]])

### ANS 6

In [31]:
neigh = KNeighborsClassifier(n_neighbors = 3, p = 1)
neigh.fit(X_train, y_train.reshape(10, ))
neigh.predict([[67, 36]])

array([1])