<a href="https://colab.research.google.com/github/kaitouz/ML-DL/blob/main/OpenEdu/task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from pandas import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv('data.csv', index_col='id')
df

X   Y  Class
id               
1   81  83      1
2   53  33      1
3   10  69      1
4   52  78      0
5   43  79      0
6   34  82      1
7   75  47      1
8   58  71      0
9   27  59      0
10  82  33      0

In [3]:
X_train = np.array(df[['X', 'Y']])
X_train

array([[81, 83],
       [53, 33],
       [10, 69],
       [52, 78],
       [43, 79],
       [34, 82],
       [75, 47],
       [58, 71],
       [27, 59],
       [82, 33]])

In [4]:
y_train = np.array(df[['Class']])
y_train

array([[1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0]])

In [5]:
import sklearn
from sklearn.neighbors import *



**Train KNN with *n_neighbors* = 1, *p* = 2 (euclidean_distance)**

In [6]:
neigh = KNeighborsClassifier(n_neighbors = 1, p = 2)
neigh.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1)

3-nearest points to [67, 36]

In [7]:
neigh.kneighbors([[67, 36]], 3, return_distance=True)

(array([[13.60147051, 14.31782106, 15.29705854]]), array([[6, 1, 9]]))

Find label with n = 3, p = 2

In [8]:
neigh = KNeighborsClassifier(n_neighbors = 3, p = 2)
neigh.fit(X_train, y_train)
neigh.predict([[67, 36]])

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([1])



---



**n_neigbors = 1, p = 1 (manhattan_distance)**

In [9]:
neigh = KNeighborsClassifier(n_neighbors = 1, p = 1)
neigh.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1, p=1)

In [16]:
neigh.kneighbors([[67, 36]], 3, return_distance=True)

(array([[17., 18., 19.]]), array([[1, 9, 6]]))

In [11]:
neigh = KNeighborsClassifier(n_neighbors = 3, p = 1)
neigh.fit(X_train, y_train)
neigh.predict([[67, 36]])

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([1])