<a href="https://colab.research.google.com/github/kaitouz/ML-DL/blob/main/OpenEdu/Test1_training_en.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Upload and change the file name

df = pd.read_csv('pulsar_stars_new.csv') 

In [ ]:
df.head()

MIP      STDIP      EKIP       SIP        MC       STDC        EKC  \
0  140.562500  55.683782 -0.234571 -0.699648  3.199833  19.110426   7.975532   
1  102.507812  58.882430  0.465318 -0.515088  1.677258  14.860146  10.576487   
2  103.015625  39.341649  0.323328  1.051164  3.121237  21.744669   7.735822   
3  136.750000  57.178449 -0.068415 -0.636238  3.642977  20.959280   6.896499   
4   88.726562  40.672225  0.600866  1.123492  1.178930  11.468720  14.269573   

           SC  TG  
0   74.242225   0  
1  127.393580   0  
2   63.171909   0  
3   53.593661   0  
4  252.567306   0

In [ ]:
# Select rows where MIP in [10, 100]  (delete rows with MIP < 10 or MIP > 100):

df_mip_droped = df.drop( df[ (df['MIP'] < 10) | (df['MIP'] > 100) ].index )
df_mip_droped.describe()     # You can find the results of the first 3 questions in the decrible() table.

MIP        STDIP         EKIP          SIP           MC  \
count  4218.000000  4218.000000  4218.000000  4218.000000  4218.000000   
mean     77.053193    40.495154     1.560447     6.695481    22.300296   
std      23.921711     6.811622     1.625623    10.435679    37.577891   
min      10.007812    24.772042     0.053681    -1.040048     0.213211   
25%      67.693359    35.893060     0.535942     1.029599     2.054975   
50%      86.773438    39.783557     0.744213     2.144131     3.535535   
75%      94.591797    44.600056     2.066990     6.402435    23.236413   
max     100.000000    85.797340     8.069522    68.101622   206.529264   

              STDC          EKC           SC           TG  
count  4218.000000  4218.000000  4218.000000  4218.000000  
mean     34.018199     7.018874    86.042132     0.340209  
std      23.828540     4.980567   106.161774     0.473835  
min       7.370432    -2.636857    -1.946039     0.000000  
25%      15.230405     2.519296     5.512367     0.000000  
50%      21.815022     7.294877    59.594262     0.000000  
75%      53.907048    10.184636   123.746712     1.000000  
max     109.655345    34.539844  1191.000837     1.000000

In [ ]:
# Ans 1
# Number of rows:
df_mip_droped.shape[0]

4218

In [ ]:
# Ans 2
# Mean value of column MIP
df_mip_droped['MIP'].mean()

77.0531927898293

In [ ]:
# Ans 3
# Max value of column SIP
df_mip_droped['SIP'].max()

68.10162173

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Split data into 2 parts: train and test
X_train, X_test, y_train, y_test = train_test_split(df_mip_droped.drop('TG', axis=1), df_mip_droped['TG'],test_size=0.3, random_state=2022)

# Scale dataset
scaler = StandardScaler().fit(X_train)   # fit scaler

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

pd.DataFrame(X_train_scaled, columns=X_train.keys()).describe()  # You can find the results of the question no.4 in the decrible() table.

MIP         STDIP          EKIP           SIP            MC  \
count  2.952000e+03  2.952000e+03  2.952000e+03  2.952000e+03  2.952000e+03   
mean  -1.581090e-16  8.286055e-16 -1.556268e-16 -5.874554e-17  2.384422e-17   
std    1.000169e+00  1.000169e+00  1.000169e+00  1.000169e+00  1.000169e+00   
min   -2.807518e+00 -2.332053e+00 -9.164943e-01 -7.415141e-01 -5.877758e-01   
25%   -3.960976e-01 -6.809554e-01 -6.319110e-01 -5.474000e-01 -5.376068e-01   
50%    4.124572e-01 -1.127319e-01 -5.040198e-01 -4.379639e-01 -4.990788e-01   
75%    7.292647e-01  6.157995e-01  3.111270e-01 -2.787460e-02  2.535213e-02   
max    9.601166e-01  6.756997e+00  3.718850e+00  5.017658e+00  4.920303e+00   

               STDC           EKC            SC  
count  2.952000e+03  2.952000e+03  2.952000e+03  
mean  -8.573013e-17  1.120754e-17 -4.121966e-17  
std    1.000169e+00  1.000169e+00  1.000169e+00  
min   -1.115491e+00 -1.947121e+00 -8.242289e-01  
25%   -7.834556e-01 -9.053585e-01 -7.535388e-01  
50%   -5.110158e-01  6.055853e-02 -2.433453e-01  
75%    8.216182e-01  6.300281e-01  3.440089e-01  
max    3.107307e+00  5.561934e+00  1.042574e+01

In [ ]:
# Ans 4
# Max value of SIP column after scale
X_train_scaled[:, 3].max()       # 3 is the order of column SIP (MIP:0, STDIP:1, EKIP:2, SIP:3, ...)

5.017657856636983

In [ ]:
from sklearn.linear_model import LogisticRegression 

clf = LogisticRegression(random_state=2022, solver='lbfgs').fit(X_train_scaled, y_train)

In [ ]:
# Ans 5
clf.coef_   # Return a list of coefficients of features (MIP, STDIP, EKIP, SIP,...) -> coefficient of MIP is the first value (= clf.coef_[0][0])

array([[ 1.39404327,  0.38737146,  6.84713889,  0.24108409, -0.79679633,
         0.73942057, -0.4093821 , -0.16971728]])

In [ ]:
# Ans 6
# Evaluation with test dataset
clf.score(X_test_scaled, y_test)

0.9344391785150079

In [ ]:
# Import new object
new_star = [136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661]   
new_star_transformed = scaler.transform([new_star])                                          # Scale new object

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
# Ans 7
# Predict the probability that it belongs to the specified class (specified class: class that has the highest probability) -> = clf.predict_proba(new_star_transformed).max()
clf.predict_proba(new_star_transformed)   # probability of new_star

array([[0.92544067, 0.07455933]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
# n_neighbors: k 
# p = 1: manhattan_distance, 2: euclidean_distance
neigh = KNeighborsClassifier(n_neighbors=5, p=2).fit(X_train_scaled, y_train)

In [ ]:
# Ans 8
neigh.predict(new_star_transformed)

array([0])

In [ ]:
# Ans 9
neigh.kneighbors(new_star_transformed)   # There are 2 Arrays: The first array is the distance of the nearest k stars to new_star, the second is their index.

(array([[1.67919448, 1.6803295 , 1.69891163, 1.74096268, 1.74311307]]),
 array([[2738, 1693, 2209, 1259, 2469]]))